image: node:lts
create-pages:
  pages:
    publish: dist
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - bash -c 'source ./dev.sh && dev setup'
  script:
    - bash -c 'source ./dev.sh && dev build'
